apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8sexamplescluster-6803"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8sexamplescluster-6803"
  template:
    metadata:
      labels:
        app: "k8sexamplescluster-6803"
    spec:
      containers:
        - name: "k8sexamplescluster-6803"
          image: "k8sexamplesacr.azurecr.io/k8sexamplescluster"
          ports:
          - containerPort: 80